// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoreThanFollowUp.Infrastructure.Context;

#nullable disable

namespace MoreThanFollowUp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930195956_Incluindo propriedade Description na tabela Sprint")]
    partial class IncluindopropriedadeDescriptionnatabelaSprint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Planning", b =>
                {
                    b.Property<int>("PlanningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanningId"));

                    b.Property<string>("DocumentationLink")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("PlanningDescription")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INT");

                    b.HasKey("PlanningId");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasFilter("[ProjectId] IS NOT NULL");

                    b.ToTable("Plannings", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Category")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("StartDate");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("EndDate");

                    b.Property<int?>("EnterpriseId")
                        .HasColumnType("INT");

                    b.Property<string>("Responsible")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Project_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DataCriacao");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INT");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SprintId"));

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("End Date");

                    b.Property<int?>("PlanningId")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Start Date");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("Link");

                    b.HasKey("SprintId");

                    b.HasIndex("PlanningId");

                    b.ToTable("Sprints", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Resources.ProjectCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Resources.ProjectResponsible", b =>
                {
                    b.Property<int>("ResponsibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponsibleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("Name");

                    b.HasKey("ResponsibleId");

                    b.ToTable("Responsible", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Resources.ProjectStatus", b =>
                {
                    b.Property<int>("StatusProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusProjectId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("Name");

                    b.HasKey("StatusProjectId");

                    b.ToTable("ProjectStatus", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CompletedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EnterpriseId")
                        .HasColumnType("INT");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Enterprise", b =>
                {
                    b.Property<int>("EnterpriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnterpriseId"));

                    b.Property<string>("CNPJ")
                        .HasColumnType("VARCHAR(18)");

                    b.Property<string>("CorporateReason")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Segment")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("INT");

                    b.HasKey("EnterpriseId");

                    b.HasIndex("TenantId");

                    b.ToTable("Enterprises", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasFilter("[SubscriptionId] IS NOT NULL");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Plan")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int?>("TenantId")
                        .IsRequired()
                        .HasColumnType("INT");

                    b.Property<int?>("TotalAvailable")
                        .HasColumnType("INT");

                    b.Property<int?>("TotalLicense")
                        .HasColumnType("INT");

                    b.Property<int?>("TotalUsed")
                        .HasColumnType("INT");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Responsible")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("TenantCustomDomain")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("TenantStatus")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("DATETIME");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoreThanFollowUp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Planning", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Entities.Projects.Project", "Project")
                        .WithOne("Planning")
                        .HasForeignKey("MoreThanFollowUp.Domain.Entities.Projects.Planning", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Project", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.Enterprise", "Enterprise")
                        .WithMany("Projects")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Project_User", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Entities.Projects.Project", "Project")
                        .WithMany("Projects_Users")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoreThanFollowUp.Domain.Models.ApplicationUser", "User")
                        .WithMany("Projects_Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Sprint", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Entities.Projects.Planning", "Planning")
                        .WithMany("Sprints")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.ApplicationUser", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.Enterprise", "Enterprise")
                        .WithMany("Users")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Enterprise", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.Tenant", "Tenant")
                        .WithMany("Enterprises")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Invoice", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.Subscription", "Subscription")
                        .WithOne("Invoice")
                        .HasForeignKey("MoreThanFollowUp.Domain.Models.Invoice", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Subscription", b =>
                {
                    b.HasOne("MoreThanFollowUp.Domain.Models.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("MoreThanFollowUp.Domain.Models.Subscription", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Planning", b =>
                {
                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Entities.Projects.Project", b =>
                {
                    b.Navigation("Planning");

                    b.Navigation("Projects_Users");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Projects_Users");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Enterprise", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Subscription", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MoreThanFollowUp.Domain.Models.Tenant", b =>
                {
                    b.Navigation("Enterprises");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
