volumes:
  sqlserver_data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver.configurator

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Criativos123@
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - sqlserver
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command: >
      bash -c "
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'Criativos123@' -d master -i docker-entrypoint-initdb.d/init.sql;
      echo 'All done!';
      "