name: Deploy to VPS

on:
  push:
    branches:
      - main  # ou outra branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan -H 191.101.18.75 >> ~/.ssh/known_hosts

    - name: Ensure target directory exists
      run: ssh root@191.101.18.75 'mkdir -p /app-mtfu'
    
    - name: Copy files to VPS
      run: scp -r ./* root@191.101.18.75:/app-mtfu

    - name: SSH and build containers
      run: |
        ssh root@191.101.18.75 << 'EOF'
          cd /app-mtfu
          if [ ! -f ".first_build_done" ]; then
            docker-compose build || { echo "Build failed"; exit 1; }
            docker-compose up || { echo "Failed to start containers"; exit 1; }
            touch .first_build_done
          else
            docker-compose build api || { echo "API build failed"; exit 1; }
            docker-compose up -d api || { echo "Failed to start API container"; exit 1; }
          fi
        EOF

