name: "Deploy para VPS"
on:
    push:
        branches:
            - main
jobs:
    build_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: "Baixar o código"
              uses: actions/checkout@v4
              
            - name: "Copiar arquivos para VPS"
              uses: appleboy/scp-action@v0.1.7
              with:
                host: "191.101.18.75"
                username: "root"
                key: "${{ secrets.SSH_PRIVATE_KEY }}"
                password: "Criativos1@"
                source: "."
                target: "/sistema"

            - name: "build da aplicação"
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: "191.101.18.75"
                username: "root"
                key: "${{ secrets.SSH_PRIVATE_KEY }}"
                password: "Criativos1@"
                script: |
                    cd /sistema
                    composes install --no-dev --no-progress -a
